//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_midtrem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tShop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tShop()
        {
            this.fItemBox = new HashSet<fItemBox>();
        }
    
        public int fID { get; set; }
        public string fName { get; set; }
        public int fPrice { get; set; }
        public string fPhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fItemBox> fItemBox { get; set; }
    }
}
